import { describe, expect, it } from 'vitest'
import { fetchExtended, parseEmbeddedJson, youtube } from './youtube'

describe('parseEmbeddedJson', () => {
	it('extracts a JSON object from a var assignment', () => {
		const html = 'var ytInitialData = {"key":"value"};'
		const result = parseEmbeddedJson(html, 'ytInitialData') as any
		expect(result).toEqual({ key: 'value' })
	})

	it('handles nested objects', () => {
		const html = 'var ytInitialData = {"a":{"b":{"c":1}}};'
		const result = parseEmbeddedJson(html, 'ytInitialData') as any
		expect(result).toEqual({ a: { b: { c: 1 } } })
	})

	it('returns null when variable not found', () => {
		const html = 'var otherVar = {"key":"value"};'
		expect(parseEmbeddedJson(html, 'ytInitialData')).toBeNull()
	})

	it('returns null on invalid JSON', () => {
		const html = 'var ytInitialData = {invalid json};'
		expect(parseEmbeddedJson(html, 'ytInitialData')).toBeNull()
	})

	it('handles surrounding HTML content', () => {
		const html =
			'<script>var foo = 1; var ytInitialData = {"ok":true}; var bar = 2;</script>'
		const result = parseEmbeddedJson(html, 'ytInitialData') as any
		expect(result).toEqual({ ok: true })
	})
})

describe('fetchExtended (integration)', { timeout: 30000 }, () => {
	it('returns music card data for an official music video', async () => {
		const result = await fetchExtended('dQw4w9WgXcQ')

		// oEmbed basics
		expect(result.provider).toBe('youtube')
		expect(result.id).toBe('dQw4w9WgXcQ')
		expect(result.title).toContain('Never Gonna Give You Up')
		expect(result.author).toBeDefined()
		expect(result.thumbnail).toBeDefined()

		// Music card enrichment
		expect(result.song).toContain('Never Gonna Give You Up')
		expect(result.artist).toBe('Rick Astley')
		expect(result.album).toBeDefined()
		expect(result.thumbnailAlbum).toBeDefined()

		// Desc header enrichment
		expect(result.channel).toBeDefined()
		expect(result.publishDate).toBeDefined()
	})

	it('returns music card data for a Topic channel video', async () => {
		// Topic channels are auto-generated by YouTube for licensed music
		const result = await fetchExtended('eNmVCcqLvH0')

		expect(result.provider).toBe('youtube')
		expect(result.id).toBe('eNmVCcqLvH0')
		expect(result.song).toBeDefined()
		expect(result.artist).toBeDefined()
		expect(result.channel).toBeDefined()
	})

	it('gracefully returns no music card for a non-music video', async () => {
		// A coding livestream — no music card expected
		const result = await fetchExtended('iu5rnQkfO6M')

		expect(result.provider).toBe('youtube')
		expect(result.id).toBe('iu5rnQkfO6M')
		expect(result.title).toBeDefined()
		// No music card, so these should be absent
		expect(result.song).toBeUndefined()
		expect(result.artist).toBeUndefined()
	})
})

describe('fetch (integration)', { timeout: 15000 }, () => {
	it('returns oEmbed metadata', async () => {
		const result = await youtube.fetch('dQw4w9WgXcQ')

		expect(result.provider).toBe('youtube')
		expect(result.id).toBe('dQw4w9WgXcQ')
		expect(result.title).toContain('Never Gonna Give You Up')
		expect(result.author).toBeDefined()
		expect(result.thumbnail).toContain('http')
	})
})
